version: '3'

services:
  postgres-master:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-master-data:
    driver: local