version: '3'

services:
  postgres-master:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - redis-data:/data

volumes:
  postgres-master-data:
    driver: local
  redis-data:
    driver: local