name: Continouos Deployment
on:
  release:
    types:
      - created

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: echo "deploying"