name: Continouos Integration/Continouos Deployment
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: run integration test
        run: make integration-test

      - name: run unit test
        run: make unit-test
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: echo "deploying"